# -*- coding: utf-8 -*-
"""лаба 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c0lpOYj55CQ0G1YvGzVeRao-z5kaTEQD
"""

import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl


import pandas as pd
import pathlib
from pathlib import Path

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

ave_file = "/content/titanic2(1).csv"

df = pd.read_csv(ave_file, sep=',')
#print(df.head())
df.head()

print(df)#вывод всей таблицы

print(df.info())#вывод столбцов

male=df[(df['Sex'] == 'male')]#количество выживших и умерших мужчин
res1 = male.groupby(['Survived'])['Survived'].count()
plt.pie(res1, labels=res1.index)
plt.title('Die and life male')
plt.show()
print(res1)

female=df[(df['Sex'] == 'female')]#количество выживших и умерших женщин
res2 = female.groupby(['Survived'])['Survived'].count()
plt.pie(res2, labels=res2.index)
plt.title('Die and life female')
plt.show()
print(res2)

female_die=df[(df['Survived'] == 0) & (df['Sex'] == 'female')]
female_non_die=df[(df['Survived'] == 1) & (df['Sex'] == 'female')]
male_die=df[(df['Survived'] == 0) & (df['Sex'] == 'male')]
male_non_die=df[(df['Survived'] == 1) & (df['Sex'] == 'male')]

res5 = female_die.groupby(['Pclass'])['Pclass'].count()
res6 = female_non_die.groupby(['Pclass'])['Pclass'].count()
res7 = male_non_die.groupby(['Pclass'])['Pclass'].count()
res8 = male_die.groupby(['Pclass'])['Pclass'].count()
plt.bar(res5, height=res5.index, label='female_die')
plt.bar(res6, height=res6.index, label='female_non_die')
plt.bar(res7, height=res7.index, label='male_non_die')
plt.bar(res8, height=res8.index, label='male_die')

plt.title ('die and life all')
plt.xlabel('number')
plt.ylabel('Pclass')
plt.legend()
plt.show()